spring.application.name=adoptions
#
spring.ai.ollama.chat.model=gemma4:26b
#
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.mvc.apiversion.default=1.1
spring.mvc.apiversion.use.header=x-dogs-version

spring.threads.virtual.enabled=true